make some tweaks to compile with ICSharpCode.Decompiler 6
icsharpcode/AvaloniaILSpy pull request #44
Opened 2020-11-15 15:30 UTC by frankli0324

6.2.1.6137 to be more precise

2020-12-03 07:22 UTC, jeffreye requested changes

2020-12-03 07:22 UTC, jeffreye commented on ILSpy.Core/DebugInfo/PortableDebugInfoProvider.cs
> +        public string SourceFileName => pdbFileName;
could you fix these code format (indents) ?

2020-12-03 07:31 UTC, jeffreye commented
Overall, the changes look good to me.

2020-12-04 02:51 UTC, frankli0324 commented
tabs or spaces? (XD

2020-12-04 05:53 UTC, jeffreye approved these changes

2020-12-04 05:54 UTC, merged